package com.codeacademy.sample.tempcalc.ui;

import java.awt.Color;


public class TemperatureCalculatorViewDesign extends javax.swing.JDialog {
	
   private static final long serialVersionUID = 1L;
   
   /**
    * Creates new form TemperatureCalculatorView
    */
   public TemperatureCalculatorViewDesign(java.awt.Frame parent, boolean modal) {
       super(parent, modal);
       initComponents();              
   }   
   
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {
	   setTitle("Temperature Calculator");
	   
       errorPanel = new javax.swing.JPanel();
       temperaturePanel = new javax.swing.JPanel();
       celciusLabel = new javax.swing.JLabel();
       celciusTextField = new javax.swing.JTextField();
       fahrenheitLabel = new javax.swing.JLabel();
       fahrenheitTextField = new javax.swing.JTextField();
       errorTextField = new javax.swing.JTextField();
       errorTextField.setForeground(Color.RED);

       setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
       setPreferredSize(new java.awt.Dimension(800, 400));
       getContentPane().setLayout(new java.awt.FlowLayout());

       errorPanel.setPreferredSize(new java.awt.Dimension(100, 30));

       javax.swing.GroupLayout errorPanelLayout = new javax.swing.GroupLayout(errorPanel);
       errorPanel.setLayout(errorPanelLayout);
       errorPanelLayout.setHorizontalGroup(
           errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 100, Short.MAX_VALUE)
       );
       errorPanelLayout.setVerticalGroup(
           errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 30, Short.MAX_VALUE)
       );

       getContentPane().add(errorPanel);

       celciusLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
       celciusLabel.setText("Celcius");

       fahrenheitLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
       fahrenheitLabel.setText("Fahrenheit");
       fahrenheitLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

       javax.swing.GroupLayout temperaturePanelLayout = new javax.swing.GroupLayout(temperaturePanel);
       temperaturePanel.setLayout(temperaturePanelLayout);
       temperaturePanelLayout.setHorizontalGroup(
           temperaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(temperaturePanelLayout.createSequentialGroup()
               .addGap(28, 28, 28)
               .addGroup(temperaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(temperaturePanelLayout.createSequentialGroup()
                       .addComponent(fahrenheitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addComponent(fahrenheitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addGroup(temperaturePanelLayout.createSequentialGroup()
                       .addComponent(celciusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addComponent(celciusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addContainerGap(250, Short.MAX_VALUE))
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, temperaturePanelLayout.createSequentialGroup()
               .addContainerGap()
               .addComponent(errorTextField)
               .addContainerGap())
       );
       temperaturePanelLayout.setVerticalGroup(
           temperaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(temperaturePanelLayout.createSequentialGroup()
               .addContainerGap()
               .addComponent(errorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(88, 88, 88)
               .addGroup(temperaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(celciusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(celciusTextField))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(temperaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(fahrenheitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(fahrenheitTextField))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );

       getContentPane().add(temperaturePanel);

       pack();
   }// </editor-fold>                        

   // Variables declaration - do not modify                     
   private javax.swing.JLabel celciusLabel;
   private javax.swing.JTextField celciusTextField;
   private javax.swing.JLabel fahrenheitLabel;
   private javax.swing.JTextField fahrenheitTextField;
   private javax.swing.JPanel temperaturePanel;
   private javax.swing.JPanel errorPanel;
   private javax.swing.JTextField errorTextField;
   // End of variables declaration                   

/**
 * @return the celciusTextField
 */
protected javax.swing.JTextField getCelciusTextField() {
	return celciusTextField;
}

/**
 * @return the fahrenheitTextField
 */
protected javax.swing.JTextField getFahrenheitTextField() {
	return fahrenheitTextField;
}

/**
 * @return the errorTextField
 */
protected javax.swing.JTextField getErrorTextField() {
	return errorTextField;
}


}

